info = new Array();
with(info) {
push(new Array("limpa", "“Pode entrar, a barra tá ______!”","Uma coisa depois de lavada.", "Uma coisa depois de lavada.", "LIMPA"));
push(new Array("galochas", "“Nossa, ele é um chato de ______!”","Um tipo de sapato que se usa na chuva ou barro.", "Um tipo de sapato que se usa na chuva ou barro.", "GALOCHAS"));
push(new Array("grilado", "“Estou ______ com a prova de matemática...”","Palavra derivada de outra que designa um inseto verde que emite um som característico.", "Palavra derivada de outra que designa um inseto verde que emite um som característico.", "GRILADO"));
push(new Array("brasa", "“Muito bem! Manda ______!”","São feitas, geralmente, de madeira queimando.", "São feitas, geralmente, de madeira queimando.", "BRASA"));
push(new Array("firme", "“Sou a garota papo-______ de que o Roberto falou”","Algo que não está frouxo.", "Algo que não está frouxo.", "FIRME"));
push(new Array("barato", "“Uau, seus anéis são um ______!”","O contrário de caro.", "O contrário de caro.", "BARATO"));
push(new Array("quadrado", "“Nossa, que homem mais ______!”","Forma geométrica de quatro ângulos.", "Forma geométrica de quatro ângulos.", "QUADRADO"));
}